# Generated by Django 6.0.1 on 2026-01-09 21:42

import at_ontology.apps.ontology_model.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('object_schema', models.JSONField(blank=True, help_text='object_schema', null=True)),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivations', to='ontology_model.datatype', verbose_name='derived_from')),
            ],
            options={
                'verbose_name': 'data_type',
                'verbose_name_plural': 'data_types',
            },
        ),
        migrations.CreateModel(
            name='ConstraintDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(choices=[('less', 'less'), ('grater', 'grater'), ('less_or_equals', 'less_or_equals'), ('grater_or_equals', 'grater_or_equals'), ('equals', 'equals'), ('not_equals', 'not_equals'), ('included', 'included'), ('not_included', 'not_included'), ('in_range', 'in_range'), ('not_in_range', 'not_in_range'), ('contains', 'contains'), ('not_contains', 'not_contains'), ('starts_with', 'starts_with'), ('ends_with', 'ends_with'), ('matches', 'matches'), ('not_matches', 'not_matches'), ('length', 'length'), ('min_length', 'min_length'), ('max_length', 'max_length')], verbose_name='constraint_type')),
                ('data', models.JSONField(validators=[at_ontology.apps.ontology_model.models.validate_constraint_data], verbose_name='constraint_data')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='ontology_model.datatype', verbose_name='data_type')),
            ],
            options={
                'verbose_name': 'constraint_definition',
                'verbose_name_plural': 'constraint_definitions',
            },
        ),
        migrations.CreateModel(
            name='OntologyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('imports', models.ManyToManyField(blank=True, related_name='ontology_model_importers', to='ontology_model.ontologymodel', verbose_name='imports')),
            ],
            options={
                'verbose_name': 'ontology_model',
                'verbose_name_plural': 'ontology_models',
            },
        ),
        migrations.AddField(
            model_name='datatype',
            name='ontology_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_types', to='ontology_model.ontologymodel', verbose_name='ontology_model'),
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='metadata')),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivations', to='ontology_model.relationshiptype', verbose_name='derived_from')),
                ('ontology_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_types', to='ontology_model.ontologymodel', verbose_name='ontology_model')),
            ],
            options={
                'verbose_name': 'relationship_type',
                'verbose_name_plural': 'relationship_types',
            },
        ),
        migrations.CreateModel(
            name='RelationshipTypeArtifactDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('default_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='default_path')),
                ('default_content', models.BinaryField(blank=True, default=None, null=True, verbose_name='default_content')),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=255, verbose_name='mime_type')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('allows_multiple', models.BooleanField(default=True, verbose_name='allows_multiple')),
                ('min_assignments', models.IntegerField(blank=True, null=True, verbose_name='min_assignments')),
                ('max_assignments', models.IntegerField(blank=True, null=True, verbose_name='max_assignments')),
                ('relationship_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ontology_model.relationshiptype', verbose_name='relationship_type')),
            ],
            options={
                'verbose_name': 'relationship_type_artifact_definition',
                'verbose_name_plural': 'relationship_type_artifact_definitions',
            },
        ),
        migrations.CreateModel(
            name='RelationshipTypePropertyDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('default', models.JSONField(blank=True, null=True, verbose_name='default_value')),
                ('initializable', models.BooleanField(default=True, verbose_name='initializable')),
                ('allows_multiple', models.BooleanField(default=True, verbose_name='allows_multiple')),
                ('min_assignments', models.IntegerField(blank=True, null=True, verbose_name='min_assignments')),
                ('max_assignments', models.IntegerField(blank=True, null=True, verbose_name='max_assignments')),
                ('relationship_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ontology_model.relationshiptype', verbose_name='relationship_type')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships_properties', to='ontology_model.datatype', verbose_name='data_type')),
            ],
            options={
                'verbose_name': 'relationship_type_property_definition',
                'verbose_name_plural': 'relationship_type_property_definitions',
            },
        ),
        migrations.CreateModel(
            name='VertexType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='metadata')),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivations', to='ontology_model.vertextype', verbose_name='derived_from')),
                ('ontology_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertex_types', to='ontology_model.ontologymodel', verbose_name='ontology_model')),
            ],
            options={
                'verbose_name': 'vertex_type',
                'verbose_name_plural': 'vertex_types',
            },
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='valid_source_types',
            field=models.ManyToManyField(blank=True, related_name='as_source_types', to='ontology_model.vertextype', verbose_name='valid_source_types'),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='valid_target_types',
            field=models.ManyToManyField(blank=True, related_name='as_target_types', to='ontology_model.vertextype', verbose_name='valid_target_types'),
        ),
        migrations.CreateModel(
            name='VertexTypeArtifactDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('default_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='default_path')),
                ('default_content', models.BinaryField(blank=True, default=None, null=True, verbose_name='default_content')),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=255, verbose_name='mime_type')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('allows_multiple', models.BooleanField(default=True, verbose_name='allows_multiple')),
                ('min_assignments', models.IntegerField(blank=True, null=True, verbose_name='min_assignments')),
                ('max_assignments', models.IntegerField(blank=True, null=True, verbose_name='max_assignments')),
                ('vertex_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ontology_model.vertextype', verbose_name='vertex_type')),
            ],
            options={
                'verbose_name': 'vertex_type_artifact_definition',
                'verbose_name_plural': 'vertex_type_artifact_definitions',
            },
        ),
        migrations.CreateModel(
            name='VertexTypePropertyDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('default', models.JSONField(blank=True, null=True, verbose_name='default_value')),
                ('initializable', models.BooleanField(default=True, verbose_name='initializable')),
                ('allows_multiple', models.BooleanField(default=True, verbose_name='allows_multiple')),
                ('min_assignments', models.IntegerField(blank=True, null=True, verbose_name='min_assignments')),
                ('max_assignments', models.IntegerField(blank=True, null=True, verbose_name='max_assignments')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertices_properties', to='ontology_model.datatype', verbose_name='data_type')),
                ('vertex_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ontology_model.vertextype', verbose_name='vertex_type')),
            ],
            options={
                'verbose_name': 'vertex_type_property_definition',
                'verbose_name_plural': 'vertex_type_property_definitions',
            },
        ),
        migrations.AddConstraint(
            model_name='ontologymodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_ontology_model'),
        ),
        migrations.AddConstraint(
            model_name='datatype',
            constraint=models.UniqueConstraint(fields=('name', 'ontology_model'), name='unique_data_type_in_model'),
        ),
        migrations.AddConstraint(
            model_name='vertextype',
            constraint=models.UniqueConstraint(fields=('name', 'ontology_model'), name='unique_vertex_type_in_model'),
        ),
        migrations.AddConstraint(
            model_name='relationshiptype',
            constraint=models.UniqueConstraint(fields=('name', 'ontology_model'), name='unique_relationship_type_in_model'),
        ),
    ]
