# Generated by Django 5.2 on 2025-04-24 18:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology_model", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationshiptype",
            name="valid_target_vertex_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="valid_relation_target_types",
                to="ontology_model.vertextype",
                verbose_name="возможные типы дочерних вершин",
            ),
        ),
    ]
