# Generated by Django 5.2 on 2025-04-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology_model", "0002_alter_relationshiptype_valid_target_vertex_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="VertexTypeNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Дополнительные данные (metadata) в виде словаря",
                        null=True,
                    ),
                ),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ссылка на сущность, из которой была получена эта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derivations",
                        to="ontology_model.vertextypenew",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.vertextypenew",
                    ),
                ),
            ],
            options={
                "verbose_name": "новый тип вершины",
                "verbose_name_plural": "новые типы вершин",
            },
        ),
    ]
