# Generated by Django 5.2 on 2025-04-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology_model", "0003_vertextypenew"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationshipTypeNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Дополнительные данные (metadata) в виде словаря",
                        null=True,
                    ),
                ),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ссылка на сущность, из которой была получена эта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derivations",
                        to="ontology_model.relationshiptypenew",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.relationshiptypenew",
                    ),
                ),
                (
                    "valid_source_vertex_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="valid_relation_source_types",
                        to="ontology_model.vertextypenew",
                        verbose_name="возможные типы родительских вершин",
                    ),
                ),
                (
                    "valid_target_vertex_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="valid_relation_target_types",
                        to="ontology_model.vertextypenew",
                        verbose_name="возможные типы дочерних вершин",
                    ),
                ),
            ],
            options={
                "verbose_name": "новый тип связи",
                "verbose_name_plural": "новые типы связей",
            },
        ),
    ]
