# Generated by Django 5.2 on 2025-04-27 18:35
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0002_remove_relationship_files_remove_vertex_files_and_more"),
        ("ontology_model", "0004_relationshiptypenew"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relationshiptypepropertydefinition",
            name="data_type",
        ),
        migrations.RemoveField(
            model_name="vertextypepropertydefinition",
            name="data_type",
        ),
        migrations.RemoveField(
            model_name="relationshiptype",
            name="derived_from",
        ),
        migrations.RemoveField(
            model_name="relationshiptype",
            name="valid_source_vertex_types",
        ),
        migrations.RemoveField(
            model_name="relationshiptype",
            name="valid_target_vertex_types",
        ),
        migrations.RemoveField(
            model_name="relationshiptypepropertydefinition",
            name="object_type",
        ),
        migrations.RemoveField(
            model_name="vertextype",
            name="derived_from",
        ),
        migrations.RemoveField(
            model_name="vertextypepropertydefinition",
            name="object_type",
        ),
        migrations.CreateModel(
            name="ArtifactAssignmentNew",
            fields=[
                ("_built", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("9ed79773-cedf-4799-96f7-b77f1900cd4a"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.artifactassignmentnew",
                    ),
                ),
            ],
            options={
                "verbose_name": "артефакт",
                "verbose_name_plural": "артефакты",
            },
        ),
        migrations.CreateModel(
            name="ArtifactDefinitionNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "default_path",
                    models.CharField(
                        blank=True,
                        help_text="Default file path for the artifact",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="application/octet-stream",
                        help_text="MIME type of the artifact",
                        max_length=255,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, help_text="Artifact is required"),
                ),
                (
                    "allows_multiple",
                    models.BooleanField(default=True, help_text="Multiple artifacts allowed"),
                ),
                (
                    "min_assignments",
                    models.IntegerField(blank=True, help_text="Minimum number of artifacts", null=True),
                ),
                (
                    "max_assignments",
                    models.IntegerField(blank=True, help_text="Maximum number of artifacts", null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.artifactdefinitionnew",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artifact Definition",
                "verbose_name_plural": "Artifact Definitions",
            },
        ),
        migrations.DeleteModel(
            name="DataType",
        ),
        migrations.DeleteModel(
            name="RelationshipType",
        ),
        migrations.DeleteModel(
            name="RelationshipTypePropertyDefinition",
        ),
        migrations.DeleteModel(
            name="VertexType",
        ),
        migrations.DeleteModel(
            name="VertexTypePropertyDefinition",
        ),
    ]
