# Generated by Django 5.2 on 2025-04-27 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ontology_model",
            "0005_remove_relationshiptypepropertydefinition_data_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactassignmentnew",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ab717824-a11b-4c0c-b5ea-4f733506073d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
