# Generated by Django 5.2 on 2025-04-27 18:52
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology_model", "0006_alter_artifactassignmentnew_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactassignmentnew",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ca93c726-deed-4119-9ad5-1abc65299cec"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
