# Generated by Django 5.2 on 2025-05-13 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ontology_model",
            "0008_rename_artifactdefinitionnew_artifactdefinition_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifactdefinition",
            name="owner",
        ),
        migrations.CreateModel(
            name="ImportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                (
                    "file",
                    models.CharField(
                        help_text="Путь или имя файла для импорта", max_length=1024
                    ),
                ),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.importdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Определение импорта",
                "verbose_name_plural": "Определения импорта",
            },
        ),
        migrations.CreateModel(
            name="RelationshipTypeArtifactDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "default_path",
                    models.CharField(
                        blank=True,
                        help_text="Default file path for the artifact",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="application/octet-stream",
                        help_text="MIME type of the artifact",
                        max_length=255,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False, help_text="Artifact is required"
                    ),
                ),
                (
                    "allows_multiple",
                    models.BooleanField(
                        default=True, help_text="Multiple artifacts allowed"
                    ),
                ),
                (
                    "min_assignments",
                    models.IntegerField(
                        blank=True, help_text="Minimum number of artifacts", null=True
                    ),
                ),
                (
                    "max_assignments",
                    models.IntegerField(
                        blank=True, help_text="Maximum number of artifacts", null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.relationshiptypeartifactdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "интенсионал типа связи",
                "verbose_name_plural": "интенсионалы типов связей",
            },
        ),
        migrations.CreateModel(
            name="RelationshipTypePropertyDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "required",
                    models.BooleanField(
                        default=False, help_text="Обязательное ли это свойство"
                    ),
                ),
                (
                    "default",
                    models.JSONField(
                        blank=True, help_text="Значение по умолчанию", null=True
                    ),
                ),
                (
                    "initializable",
                    models.BooleanField(
                        default=True,
                        help_text="Можно ли инициализировать значение при создании",
                    ),
                ),
                (
                    "allows_multiple",
                    models.BooleanField(
                        default=True, help_text="Разрешать несколько значений"
                    ),
                ),
                (
                    "min_assignments",
                    models.IntegerField(
                        blank=True, help_text="Минимальное число присвоений", null=True
                    ),
                ),
                (
                    "max_assignments",
                    models.IntegerField(
                        blank=True, help_text="Максимальное число присвоений", null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.relationshiptypepropertydefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "relationship type property definition",
                "verbose_name_plural": "relationship type property definitions",
            },
        ),
        migrations.CreateModel(
            name="VertexTypeArtifactDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "default_path",
                    models.CharField(
                        blank=True,
                        help_text="Default file path for the artifact",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="application/octet-stream",
                        help_text="MIME type of the artifact",
                        max_length=255,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False, help_text="Artifact is required"
                    ),
                ),
                (
                    "allows_multiple",
                    models.BooleanField(
                        default=True, help_text="Multiple artifacts allowed"
                    ),
                ),
                (
                    "min_assignments",
                    models.IntegerField(
                        blank=True, help_text="Minimum number of artifacts", null=True
                    ),
                ),
                (
                    "max_assignments",
                    models.IntegerField(
                        blank=True, help_text="Maximum number of artifacts", null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.vertextypeartifactdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "интенсионал типа вершины",
                "verbose_name_plural": "интенсионалы типов вершин",
            },
        ),
        migrations.CreateModel(
            name="VertexTypePropertyDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "required",
                    models.BooleanField(
                        default=False, help_text="Обязательное ли это свойство"
                    ),
                ),
                (
                    "default",
                    models.JSONField(
                        blank=True, help_text="Значение по умолчанию", null=True
                    ),
                ),
                (
                    "initializable",
                    models.BooleanField(
                        default=True,
                        help_text="Можно ли инициализировать значение при создании",
                    ),
                ),
                (
                    "allows_multiple",
                    models.BooleanField(
                        default=True, help_text="Разрешать несколько значений"
                    ),
                ),
                (
                    "min_assignments",
                    models.IntegerField(
                        blank=True, help_text="Минимальное число присвоений", null=True
                    ),
                ),
                (
                    "max_assignments",
                    models.IntegerField(
                        blank=True, help_text="Максимальное число присвоений", null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.vertextypepropertydefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "vertex type property definition",
                "verbose_name_plural": "vertex type property definitions",
            },
        ),
        migrations.DeleteModel(
            name="ArtifactAssignment",
        ),
        migrations.DeleteModel(
            name="ArtifactDefinition",
        ),
    ]
