# Generated by Django 5.2 on 2025-05-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ontology_model",
            "0009_remove_artifactdefinition_owner_importdefinition_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vertextype",
            options={
                "verbose_name": "тип вершины",
                "verbose_name_plural": "типы вершин",
            },
        ),
        migrations.CreateModel(
            name="OntologyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.ontologymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "модель онтологии",
                "verbose_name_plural": "модели онтологии",
            },
        ),
    ]
