# Generated by Django 5.2 on 2025-05-14 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology_model", "0010_alter_vertextype_options_ontologymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ontologymodel",
            name="imports",
            field=models.ManyToManyField(
                blank=True,
                related_name="import_definitions",
                to="ontology_model.importdefinition",
                verbose_name="Импорты",
            ),
        ),
        migrations.AddField(
            model_name="relationshiptype",
            name="ontology_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationship_types",
                to="ontology_model.ontologymodel",
            ),
        ),
        migrations.AddField(
            model_name="vertextype",
            name="ontology_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertex_types",
                to="ontology_model.ontologymodel",
            ),
        ),
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ссылка на сущность, из которой была получена эта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derivations",
                        to="ontology_model.datatype",
                    ),
                ),
                (
                    "ontology_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_types",
                        to="ontology_model.ontologymodel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology_model.datatype",
                    ),
                ),
            ],
            options={
                "verbose_name": "тип данных",
                "verbose_name_plural": "типы данных",
            },
        ),
    ]
