# Generated by Django 5.2 on 2025-05-16 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology_model", "0011_ontologymodel_imports_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relationshiptype",
            options={"verbose_name": "тип связи", "verbose_name_plural": "типы связей"},
        ),
        migrations.AlterField(
            model_name="relationshiptype",
            name="ontology_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationship_types",
                to="ontology_model.ontologymodel",
            ),
        ),
        migrations.AlterField(
            model_name="vertextype",
            name="ontology_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertex_types",
                to="ontology_model.ontologymodel",
            ),
        ),
    ]
