# Generated by Django 5.2 on 2025-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology_model", "0012_alter_relationshiptype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datatype",
            name="object_schema",
            field=models.JSONField(
                blank=True, help_text="Raw schema as JSON string", null=True
            ),
        ),
    ]
