# Generated by Django 5.2 on 2025-05-19 20:15
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology_model", "0013_datatype_object_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshiptypepropertydefinition",
            name="ontology_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationship_types_property_definitions",
                to="ontology_model.ontologymodel",
            ),
        ),
        migrations.AddField(
            model_name="relationshiptypepropertydefinition",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="relationship_types_property_definitions",
                to="ontology_model.datatype",
            ),
        ),
        migrations.AddField(
            model_name="vertextypepropertydefinition",
            name="ontology_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertex_types_property_definitions",
                to="ontology_model.ontologymodel",
            ),
        ),
        migrations.AddField(
            model_name="vertextypepropertydefinition",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vertex_types_property_definitions",
                to="ontology_model.datatype",
            ),
        ),
    ]
