# Generated by Django 5.2.4 on 2025-07-23 15:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology_model", "0015_remove_datatype__built_remove_datatype_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ontologymodel",
            name="imports",
            field=models.ManyToManyField(
                blank=True,
                related_name="ontology_model_importers",
                to="ontology_model.ontologymodel",
                verbose_name="Импорты",
            ),
        ),
    ]
