# Generated by Django 5.2.9 on 2025-12-23 16:02

import at_ontology.apps.ontology_model.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology_model', '0016_alter_ontologymodel_imports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': 'data_type', 'verbose_name_plural': 'data_types'},
        ),
        migrations.AlterModelOptions(
            name='ontologymodel',
            options={'verbose_name': 'ontology_model', 'verbose_name_plural': 'ontology_models'},
        ),
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'verbose_name': 'relationship_type', 'verbose_name_plural': 'relationship_types'},
        ),
        migrations.AlterModelOptions(
            name='relationshiptypeartifactdefinition',
            options={'verbose_name': 'relationship_type_artifact_definition', 'verbose_name_plural': 'relationship_type_artifact_definitions'},
        ),
        migrations.AlterModelOptions(
            name='relationshiptypepropertydefinition',
            options={'verbose_name': 'relationship_type_property_definition', 'verbose_name_plural': 'relationship_type_property_definitions'},
        ),
        migrations.AlterModelOptions(
            name='vertextype',
            options={'verbose_name': 'vertex_type', 'verbose_name_plural': 'vertex_types'},
        ),
        migrations.AlterModelOptions(
            name='vertextypeartifactdefinition',
            options={'verbose_name': 'vertex_type_artifact_definition', 'verbose_name_plural': 'vertex_type_artifact_definitions'},
        ),
        migrations.AlterModelOptions(
            name='vertextypepropertydefinition',
            options={'verbose_name': 'vertex_type_property_definition', 'verbose_name_plural': 'vertex_type_property_definitions'},
        ),
        migrations.AlterField(
            model_name='datatype',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivations', to='ontology_model.datatype', verbose_name='derived_from'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='object_schema',
            field=models.JSONField(blank=True, help_text='object_schema', null=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='ontology_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_types', to='ontology_model.ontologymodel', verbose_name='ontology_model'),
        ),
        migrations.AlterField(
            model_name='ontologymodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ontologymodel',
            name='imports',
            field=models.ManyToManyField(blank=True, related_name='ontology_model_importers', to='ontology_model.ontologymodel', verbose_name='imports'),
        ),
        migrations.AlterField(
            model_name='ontologymodel',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='ontologymodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivations', to='ontology_model.relationshiptype', verbose_name='derived_from'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='ontology_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_types', to='ontology_model.ontologymodel', verbose_name='ontology_model'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='valid_source_vertex_types',
            field=models.ManyToManyField(blank=True, related_name='valid_source_types', to='ontology_model.vertextype', verbose_name='valid_source_vertex_types'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='valid_target_vertex_types',
            field=models.ManyToManyField(blank=True, related_name='valid_target_types', to='ontology_model.vertextype', verbose_name='valid_target_vertex_types'),
        ),
        migrations.AlterField(
            model_name='relationshiptypeartifactdefinition',
            name='allows_multiple',
            field=models.BooleanField(default=True, verbose_name='allows_multiple'),
        ),
        migrations.AlterField(
            model_name='relationshiptypeartifactdefinition',
            name='default_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default_path'),
        ),
        migrations.AlterField(
            model_name='relationshiptypeartifactdefinition',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='relationshiptypeartifactdefinition',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='relationshiptypeartifactdefinition',
            name='max_assignments',
            field=models.IntegerField(blank=True, null=True, verbose_name='max_assignments'),
        ),
        migrations.AlterField(
            model_name='relationshiptypeartifactdefinition',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=255, verbose_name='mime_type'),
        ),
        migrations.AlterField(
            model_name='relationshiptypeartifactdefinition',
            name='min_assignments',
            field=models.IntegerField(blank=True, null=True, verbose_name='min_assignments'),
        ),
        migrations.AlterField(
            model_name='relationshiptypeartifactdefinition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relationshiptypeartifactdefinition',
            name='relationship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ontology_model.relationshiptype', verbose_name='relationship_type'),
        ),
        migrations.AlterField(
            model_name='relationshiptypeartifactdefinition',
            name='required',
            field=models.BooleanField(default=False, verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='allows_multiple',
            field=models.BooleanField(default=True, verbose_name='allows_multiple'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='default',
            field=models.JSONField(blank=True, null=True, verbose_name='default_value'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='initializable',
            field=models.BooleanField(default=True, verbose_name='initializable'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='max_assignments',
            field=models.IntegerField(blank=True, null=True, verbose_name='max_assignments'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='min_assignments',
            field=models.IntegerField(blank=True, null=True, verbose_name='min_assignments'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='relationship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ontology_model.relationshiptype', verbose_name='relationship_type'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='required',
            field=models.BooleanField(default=False, verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='relationshiptypepropertydefinition',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships_properties', to='ontology_model.datatype', verbose_name='data_type'),
        ),
        migrations.AlterField(
            model_name='vertextype',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivations', to='ontology_model.vertextype', verbose_name='derived_from'),
        ),
        migrations.AlterField(
            model_name='vertextype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='vertextype',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='vertextype',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='vertextype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='vertextype',
            name='ontology_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertex_types', to='ontology_model.ontologymodel', verbose_name='ontology_model'),
        ),
        migrations.AlterField(
            model_name='vertextypeartifactdefinition',
            name='allows_multiple',
            field=models.BooleanField(default=True, verbose_name='allows_multiple'),
        ),
        migrations.AlterField(
            model_name='vertextypeartifactdefinition',
            name='default_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='default_path'),
        ),
        migrations.AlterField(
            model_name='vertextypeartifactdefinition',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='vertextypeartifactdefinition',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='vertextypeartifactdefinition',
            name='max_assignments',
            field=models.IntegerField(blank=True, null=True, verbose_name='max_assignments'),
        ),
        migrations.AlterField(
            model_name='vertextypeartifactdefinition',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=255, verbose_name='mime_type'),
        ),
        migrations.AlterField(
            model_name='vertextypeartifactdefinition',
            name='min_assignments',
            field=models.IntegerField(blank=True, null=True, verbose_name='min_assignments'),
        ),
        migrations.AlterField(
            model_name='vertextypeartifactdefinition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='vertextypeartifactdefinition',
            name='required',
            field=models.BooleanField(default=False, verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='vertextypeartifactdefinition',
            name='vertex_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ontology_model.vertextype', verbose_name='vertex_type'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='allows_multiple',
            field=models.BooleanField(default=True, verbose_name='allows_multiple'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='default',
            field=models.JSONField(blank=True, null=True, verbose_name='default_value'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='initializable',
            field=models.BooleanField(default=True, verbose_name='initializable'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='max_assignments',
            field=models.IntegerField(blank=True, null=True, verbose_name='max_assignments'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='min_assignments',
            field=models.IntegerField(blank=True, null=True, verbose_name='min_assignments'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='required',
            field=models.BooleanField(default=False, verbose_name='required'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertices_properties', to='ontology_model.datatype', verbose_name='data_type'),
        ),
        migrations.AlterField(
            model_name='vertextypepropertydefinition',
            name='vertex_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ontology_model.vertextype', verbose_name='vertex_type'),
        ),
        migrations.CreateModel(
            name='ConstraintDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('less', 'less'), ('grater', 'grater'), ('less_or_equals', 'less_or_equals'), ('grater_or_equals', 'grater_or_equals'), ('equals', 'equals'), ('not_equals', 'not_equals'), ('included', 'included'), ('not_included', 'not_included'), ('in_range', 'in_range'), ('not_in_range', 'not_in_range'), ('contains', 'contains'), ('not_contains', 'not_contains'), ('starts_with', 'starts_with'), ('ends_with', 'ends_with'), ('matches', 'matches'), ('not_matches', 'not_matches'), ('length', 'length'), ('min_length', 'min_length'), ('max_length', 'max_length')], verbose_name='constraint_type')),
                ('data', models.JSONField(validators=[at_ontology.apps.ontology_model.models.validate_constraint_data], verbose_name='constraint_data')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='ontology_model.datatype', verbose_name='data_type')),
            ],
            options={
                'verbose_name': 'constraint_definition',
                'verbose_name_plural': 'constraint_definitions',
            },
        ),
    ]
