# Generated by Django 5.2.9 on 2025-12-27 11:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology_model", "0017_alter_datatype_options_alter_ontologymodel_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relationshiptype",
            name="valid_source_vertex_types",
        ),
        migrations.RemoveField(
            model_name="relationshiptype",
            name="valid_target_vertex_types",
        ),
        migrations.AddField(
            model_name="relationshiptype",
            name="valid_source_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="as_source_types",
                to="ontology_model.vertextype",
                verbose_name="valid_source_types",
            ),
        ),
        migrations.AddField(
            model_name="relationshiptype",
            name="valid_target_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="as_target_types",
                to="ontology_model.vertextype",
                verbose_name="valid_target_types",
            ),
        ),
    ]
