# Generated by Django 5.2.9 on 2025-12-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology_model', '0018_remove_relationshiptype_valid_source_vertex_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptypeartifactdefinition',
            name='default_content',
            field=models.BinaryField(blank=True, default=None, null=True, verbose_name='default_content'),
        ),
        migrations.AddField(
            model_name='vertextypeartifactdefinition',
            name='default_content',
            field=models.BinaryField(blank=True, default=None, null=True, verbose_name='default_content'),
        ),
    ]
