# Generated by Django 6.0 on 2026-01-06 16:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology_model", "0019_relationshiptypeartifactdefinition_default_content_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="datatype",
            constraint=models.UniqueConstraint(fields=("name", "ontology_model"), name="unique_data_type_in_model"),
        ),
        migrations.AddConstraint(
            model_name="ontologymodel",
            constraint=models.UniqueConstraint(fields=("name",), name="unique_ontology_model"),
        ),
        migrations.AddConstraint(
            model_name="relationshiptype",
            constraint=models.UniqueConstraint(
                fields=("name", "ontology_model"), name="unique_relationship_type_in_model"
            ),
        ),
        migrations.AddConstraint(
            model_name="vertextype",
            constraint=models.UniqueConstraint(fields=("name", "ontology_model"), name="unique_vertex_type_in_model"),
        ),
    ]
