# Generated by Django 4.0.6 on 2022-07-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0003_file_extension_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='element',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Содержимое'),
        ),
    ]
