# Generated by Django 4.0.6 on 2022-07-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0004_relation_data_alter_element_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='files',
            field=models.ManyToManyField(blank=True, to='ontology.file', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='transitivity',
            field=models.IntegerField(choices=[(0, 'По умолчанию'), (1, 'Transitive'), (2, 'Intransitive')], default=0, verbose_name='Транзитивность'),
        ),
    ]
