# Generated by Django 4.0.6 on 2022-07-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementtype',
            options={'verbose_name': 'Тип элемента', 'verbose_name_plural': 'Типы элементов'},
        ),
        migrations.AlterModelOptions(
            name='relationtype',
            options={'verbose_name': 'Тип связи', 'verbose_name_plural': 'Типы связей'},
        ),
        migrations.AddField(
            model_name='relationtype',
            name='default_reflexivity',
            field=models.IntegerField(blank=True, choices=[(None, 'Не указано'), (1, 'Рефлексивно'), (2, 'Антирефлексивно')], default=None, null=True, verbose_name='Рефлексивность по умолчанию'),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='default_symmetry',
            field=models.IntegerField(blank=True, choices=[(None, 'Не указано'), (1, 'Симментрично'), (2, 'Антисиметрично')], default=None, null=True, verbose_name='Симметричность по умолчанию'),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='default_transitivity',
            field=models.IntegerField(choices=[(1, 'Транзитивно'), (2, 'Интранзитивно')], default=2, verbose_name='Транзитивность по умолчанию'),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
