# Generated by Django 6.0.1 on 2026-01-09 21:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ontology_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('imports', models.ManyToManyField(blank=True, related_name='ontology_importers', to='ontology_model.ontologymodel', verbose_name='imports')),
            ],
            options={
                'verbose_name': 'ontology',
                'verbose_name_plural': 'ontologies',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='metadata')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='ontology.ontology', verbose_name='ontology')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='ontology_model.relationshiptype', verbose_name='relationship_type')),
            ],
            options={
                'verbose_name': 'relationship',
                'verbose_name_plural': 'relationships',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipArtifactAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='path')),
                ('content', models.BinaryField(blank=True, null=True, verbose_name='content')),
                ('definition', models.ForeignKey(help_text='artifact_definition_used', on_delete=django.db.models.deletion.CASCADE, related_name='relationship_artifacts', to='ontology_model.relationshiptypeartifactdefinition', verbose_name='artifact_definition')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ontology.relationship', verbose_name='relationship')),
            ],
            options={
                'verbose_name': 'relationship_artifact_assignment',
                'verbose_name_plural': 'relationship_artifact_assignments',
            },
        ),
        migrations.CreateModel(
            name='RelationshipPropertyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('value', models.JSONField(verbose_name='value')),
                ('definition', models.ForeignKey(help_text='property_definition_used', on_delete=django.db.models.deletion.CASCADE, related_name='relationship_properties', to='ontology_model.relationshiptypepropertydefinition', verbose_name='property_definition')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ontology.relationship', verbose_name='relationship')),
            ],
            options={
                'verbose_name': 'relationship_property_assignment',
                'verbose_name_plural': 'relationship_property_assignments',
            },
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='metadata')),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertices', to='ontology.ontology', verbose_name='ontology')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vertex_type', to='ontology_model.vertextype', verbose_name='vertex_type')),
            ],
            options={
                'verbose_name': 'vertex',
                'verbose_name_plural': 'vertices',
            },
        ),
        migrations.AddField(
            model_name='relationship',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_relationships', to='ontology.vertex', verbose_name='source_vertex'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_relationships', to='ontology.vertex', verbose_name='target_vertex'),
        ),
        migrations.CreateModel(
            name='VertexArtifactAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='path')),
                ('content', models.BinaryField(blank=True, null=True, verbose_name='content')),
                ('definition', models.ForeignKey(help_text='artifact_definition_used', on_delete=django.db.models.deletion.CASCADE, related_name='vertex_artifacts', to='ontology_model.vertextypeartifactdefinition', verbose_name='artifact_definition')),
                ('vertex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ontology.vertex', verbose_name='vertex')),
            ],
            options={
                'verbose_name': 'vertex_artifact_assignment',
                'verbose_name_plural': 'vertex_artifact_assignments',
            },
        ),
        migrations.CreateModel(
            name='VertexPropertyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('value', models.JSONField(verbose_name='value')),
                ('definition', models.ForeignKey(help_text='property_definition_used', on_delete=django.db.models.deletion.CASCADE, related_name='vertex_properties', to='ontology_model.vertextypepropertydefinition', verbose_name='property_definition')),
                ('vertex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ontology.vertex', verbose_name='vertex')),
            ],
            options={
                'verbose_name': 'vertex_property_assignment',
                'verbose_name_plural': 'vertex_property_assignments',
            },
        ),
        migrations.AddConstraint(
            model_name='ontology',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_ontology'),
        ),
        migrations.AddConstraint(
            model_name='vertex',
            constraint=models.UniqueConstraint(fields=('name', 'ontology'), name='unique_vertex_in_ontology'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('name', 'ontology'), name='unique_relationship_in_ontology'),
        ),
    ]
