# Generated by Django 5.1.6 on 2025-02-05 19:45
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ontology_model", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("content", models.FileField(upload_to="", verbose_name="содержимое")),
            ],
            options={
                "verbose_name": "файл",
                "verbose_name_plural": "файлы",
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True, verbose_name="имя")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание")),
                ("files", models.ManyToManyField(blank=True, to="ontology.file", verbose_name="файлы")),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="ontology_model.relationshiptype",
                        verbose_name="тип связи",
                    ),
                ),
            ],
            options={
                "verbose_name": "связь",
                "verbose_name_plural": "связи",
            },
        ),
        migrations.CreateModel(
            name="RelationshipPropertyAssignments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.JSONField(blank=True, null=True, verbose_name="значение")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ontology_model.relationshiptypepropertydefinition",
                        verbose_name="исходное свойство типа связи",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="ontology.relationship",
                        verbose_name="связь",
                    ),
                ),
            ],
            options={
                "verbose_name": "присвоенное значение свойства связи",
                "verbose_name_plural": "присвоенные значения свойств связей",
            },
        ),
        migrations.CreateModel(
            name="Vertex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="имя")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание")),
                ("files", models.ManyToManyField(blank=True, to="ontology.file", verbose_name="Файлы")),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="ontology_model.vertextype",
                        verbose_name="тип вершины",
                    ),
                ),
            ],
            options={
                "verbose_name": "вершина",
                "verbose_name_plural": "вершины",
            },
        ),
        migrations.AddField(
            model_name="relationship",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="output_relations",
                to="ontology.vertex",
                verbose_name="родительская вершина",
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input_relations",
                to="ontology.vertex",
                verbose_name="дочерняя вершина",
            ),
        ),
        migrations.CreateModel(
            name="VertexPropertyAssignments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.JSONField(blank=True, null=True, verbose_name="значение")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ontology_model.vertextypepropertydefinition",
                        verbose_name="исходное свойство типа вершины",
                    ),
                ),
                (
                    "vertex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="ontology.vertex",
                        verbose_name="вершина",
                    ),
                ),
            ],
            options={
                "verbose_name": "присвоенное значение свойства вершины",
                "verbose_name_plural": "присвоенные значения свойств вершин",
            },
        ),
    ]
