# Generated by Django 5.2 on 2025-04-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relationship",
            name="files",
        ),
        migrations.RemoveField(
            model_name="vertex",
            name="files",
        ),
        migrations.RemoveField(
            model_name="vertex",
            name="ontology",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="source",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="target",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="type",
        ),
        migrations.RemoveField(
            model_name="relationshippropertyassignment",
            name="object",
        ),
        migrations.RemoveField(
            model_name="relationshippropertyassignment",
            name="property",
        ),
        migrations.RemoveField(
            model_name="vertex",
            name="type",
        ),
        migrations.RemoveField(
            model_name="vertexpropertyassignment",
            name="object",
        ),
        migrations.RemoveField(
            model_name="vertexpropertyassignment",
            name="property",
        ),
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="Ontology",
        ),
        migrations.DeleteModel(
            name="Relationship",
        ),
        migrations.DeleteModel(
            name="RelationshipPropertyAssignment",
        ),
        migrations.DeleteModel(
            name="Vertex",
        ),
        migrations.DeleteModel(
            name="VertexPropertyAssignment",
        ),
    ]
