# Generated by Django 5.2 on 2025-04-27 18:40
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ontology", "0002_remove_relationship_files_remove_vertex_files_and_more"),
        ("ontology_model", "0006_alter_artifactassignmentnew_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="VertexNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata stored as a JSON object",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology.vertexnew",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vertex_type",
                        to="ontology_model.vertextypenew",
                    ),
                ),
            ],
            options={
                "verbose_name": "вершина",
                "verbose_name_plural": "вершины",
            },
        ),
    ]
