# Generated by Django 5.2 on 2025-04-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0003_initial"),
        ("ontology_model", "0007_alter_artifactassignmentnew_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationshipNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata stored as a JSON object",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology.relationshipnew",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationship",
                        to="ontology.vertexnew",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationship",
                        to="ontology.vertexnew",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relationships",
                        to="ontology_model.relationshiptypenew",
                    ),
                ),
            ],
            options={
                "verbose_name": "связь",
                "verbose_name_plural": "связи",
                "ordering": ["type"],
            },
        ),
    ]
