# Generated by Django 5.2 on 2025-04-27 19:24
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0004_relationshipnew"),
        ("ontology_model", "0007_alter_artifactassignmentnew_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RelationshipNew",
            new_name="Relationship",
        ),
        migrations.RenameModel(
            old_name="VertexNew",
            new_name="Vertex",
        ),
    ]
