# Generated by Django 5.2 on 2025-05-13 18:13
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0006_relationshipartifactassignment_and_more"),
        ("ontology_model", "0010_alter_vertextype_options_ontologymodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relationshippropertyassignment",
            options={
                "verbose_name": "свойство связи",
                "verbose_name_plural": "свойства связей",
            },
        ),
        migrations.AlterField(
            model_name="relationshipartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9ece0442-bec2-4043-b9c9-f16d9a203941"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9ece0442-bec2-4043-b9c9-f16d9a203941"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="vertex_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertex_type_artifact_assignments",
                to="ontology_model.vertextype",
            ),
        ),
        migrations.CreateModel(
            name="Ontology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_built", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ontology.ontology",
                    ),
                ),
            ],
            options={
                "verbose_name": "онтология",
                "verbose_name_plural": "онтологии",
            },
        ),
        migrations.AddField(
            model_name="relationship",
            name="ontology",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="ontology.ontology",
            ),
        ),
        migrations.AddField(
            model_name="vertex",
            name="ontology",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertices",
                to="ontology.ontology",
            ),
        ),
    ]
