# Generated by Django 5.2 on 2025-05-14 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0007_alter_relationshippropertyassignment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationshipartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a12c732d-1b1f-4ce5-ace0-5470ecbc47f1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a12c732d-1b1f-4ce5-ace0-5470ecbc47f1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
