# Generated by Django 5.2 on 2025-05-16 09:45
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0008_alter_relationshipartifactassignment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="ontology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="ontology.ontology",
            ),
        ),
        migrations.AlterField(
            model_name="relationshipartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1c6f085e-2a1e-4b37-af61-ea3d4ecc6afb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertex",
            name="ontology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertices",
                to="ontology.ontology",
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1c6f085e-2a1e-4b37-af61-ea3d4ecc6afb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
