# Generated by Django 5.2 on 2025-05-19 19:47
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0009_alter_relationship_ontology_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationshipartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a538aaf-00e9-4a02-a54d-d4f821699ab5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a538aaf-00e9-4a02-a54d-d4f821699ab5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
