# Generated by Django 5.2 on 2025-05-19 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0010_alter_relationshipartifactassignment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationshipartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("942a7176-4e4f-4bb4-b12e-88f69272fc9d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("942a7176-4e4f-4bb4-b12e-88f69272fc9d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
