# Generated by Django 5.2 on 2025-05-20 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0011_alter_relationshipartifactassignment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshipartifactassignment",
            name="content",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vertexartifactassignment",
            name="content",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="relationshipartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("35185a3a-378a-4572-9e5b-d26aa30e42a0"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("35185a3a-378a-4572-9e5b-d26aa30e42a0"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
