# Generated by Django 5.2.4 on 2025-07-23 15:05
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0012_relationshipartifactassignment_content_and_more"),
        ("ontology_model", "0015_remove_datatype__built_remove_datatype_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ontology",
            name="_built",
        ),
        migrations.RemoveField(
            model_name="ontology",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="_built",
        ),
        migrations.RemoveField(
            model_name="relationship",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="relationshipartifactassignment",
            name="_built",
        ),
        migrations.RemoveField(
            model_name="relationshipartifactassignment",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="relationshipartifactassignment",
            name="relationship_type",
        ),
        migrations.RemoveField(
            model_name="relationshippropertyassignment",
            name="_built",
        ),
        migrations.RemoveField(
            model_name="relationshippropertyassignment",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="relationshippropertyassignment",
            name="relationship_type",
        ),
        migrations.RemoveField(
            model_name="vertex",
            name="_built",
        ),
        migrations.RemoveField(
            model_name="vertex",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="vertexartifactassignment",
            name="_built",
        ),
        migrations.RemoveField(
            model_name="vertexartifactassignment",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="vertexartifactassignment",
            name="vertex_type",
        ),
        migrations.RemoveField(
            model_name="vertexpropertyassignment",
            name="_built",
        ),
        migrations.RemoveField(
            model_name="vertexpropertyassignment",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="vertexpropertyassignment",
            name="vertex_type",
        ),
        migrations.AddField(
            model_name="ontology",
            name="imports",
            field=models.ManyToManyField(
                blank=True, related_name="import_definitions", to="ontology_model.ontologymodel", verbose_name="Импорты"
            ),
        ),
        migrations.AlterField(
            model_name="relationshipartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1d8704ef-7091-4adf-b03b-8b9af29b9b6a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1d8704ef-7091-4adf-b03b-8b9af29b9b6a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
