# Generated by Django 5.2.4 on 2025-07-23 15:08
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0013_remove_ontology__built_remove_ontology_owner_and_more"),
        ("ontology_model", "0016_alter_ontologymodel_imports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ontology",
            name="imports",
            field=models.ManyToManyField(
                blank=True, related_name="ontology_importers", to="ontology_model.ontologymodel", verbose_name="Импорты"
            ),
        ),
        migrations.AlterField(
            model_name="relationshipartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d593fad0-2be4-40de-bbc1-4f80ef8a9467"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d593fad0-2be4-40de-bbc1-4f80ef8a9467"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
