# Generated by Django 5.2.4 on 2025-07-23 15:28
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0014_alter_ontology_imports_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationshipartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f6a5c38b-db22-44f0-a2df-1e520cb3db43"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f6a5c38b-db22-44f0-a2df-1e520cb3db43"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
