# Generated by Django 5.2.4 on 2025-07-23 15:53
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0015_alter_relationshipartifactassignment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationshipartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cace8590-3cc8-4936-9328-febc5017ba4e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="vertexartifactassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cace8590-3cc8-4936-9328-febc5017ba4e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
