# Generated by Django 5.2.9 on 2025-12-23 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0017_alter_relationshipartifactassignment_id_and_more'),
        ('ontology_model', '0017_alter_datatype_options_alter_ontologymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ontology',
            options={'verbose_name': 'ontology', 'verbose_name_plural': 'ontologies'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['type'], 'verbose_name': 'relationship', 'verbose_name_plural': 'relationships'},
        ),
        migrations.AlterModelOptions(
            name='relationshipartifactassignment',
            options={'verbose_name': 'relationship_artifact_assignment', 'verbose_name_plural': 'relationship_artifact_assignments'},
        ),
        migrations.AlterModelOptions(
            name='relationshippropertyassignment',
            options={'verbose_name': 'relationship_property_assignment', 'verbose_name_plural': 'relationship_property_assignments'},
        ),
        migrations.AlterModelOptions(
            name='vertex',
            options={'verbose_name': 'vertex', 'verbose_name_plural': 'vertices'},
        ),
        migrations.AlterModelOptions(
            name='vertexartifactassignment',
            options={'verbose_name': 'vertex_artifact_assignment', 'verbose_name_plural': 'vertex_artifact_assignments'},
        ),
        migrations.AlterModelOptions(
            name='vertexpropertyassignment',
            options={'verbose_name': 'vertex_property_assignment', 'verbose_name_plural': 'vertex_property_assignments'},
        ),
        migrations.AlterField(
            model_name='ontology',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='imports',
            field=models.ManyToManyField(blank=True, related_name='ontology_importers', to='ontology_model.ontologymodel', verbose_name='imports'),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='ontology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='ontology.ontology', verbose_name='ontology'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_relationships', to='ontology.vertex', verbose_name='source_vertex'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_relationships', to='ontology.vertex', verbose_name='target_vertex'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='ontology_model.relationshiptype', verbose_name='relationship_type'),
        ),
        migrations.AlterField(
            model_name='relationshipartifactassignment',
            name='content',
            field=models.BinaryField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='relationshipartifactassignment',
            name='definition',
            field=models.ForeignKey(help_text='artifact_definition_used', on_delete=django.db.models.deletion.CASCADE, related_name='relationship_artifacts', to='ontology_model.relationshiptypeartifactdefinition', verbose_name='artifact_definition'),
        ),
        migrations.AlterField(
            model_name='relationshipartifactassignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='relationshipartifactassignment',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='relationshipartifactassignment',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ontology.relationship', verbose_name='relationship'),
        ),
        migrations.AlterField(
            model_name='relationshippropertyassignment',
            name='definition',
            field=models.ForeignKey(help_text='property_definition_used', on_delete=django.db.models.deletion.CASCADE, related_name='relationship_properties', to='ontology_model.relationshiptypepropertydefinition', verbose_name='property_definition'),
        ),
        migrations.AlterField(
            model_name='relationshippropertyassignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='relationshippropertyassignment',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ontology.relationship', verbose_name='relationship'),
        ),
        migrations.AlterField(
            model_name='relationshippropertyassignment',
            name='value',
            field=models.JSONField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='ontology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertices', to='ontology.ontology', verbose_name='ontology'),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vertex_type', to='ontology_model.vertextype', verbose_name='vertex_type'),
        ),
        migrations.AlterField(
            model_name='vertexartifactassignment',
            name='content',
            field=models.BinaryField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='vertexartifactassignment',
            name='definition',
            field=models.ForeignKey(help_text='artifact_definition_used', on_delete=django.db.models.deletion.CASCADE, related_name='vertex_artifacts', to='ontology_model.vertextypeartifactdefinition', verbose_name='artifact_definition'),
        ),
        migrations.AlterField(
            model_name='vertexartifactassignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='vertexartifactassignment',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='vertexartifactassignment',
            name='vertex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ontology.vertex', verbose_name='vertex'),
        ),
        migrations.AlterField(
            model_name='vertexpropertyassignment',
            name='definition',
            field=models.ForeignKey(help_text='property_definition_used', on_delete=django.db.models.deletion.CASCADE, related_name='vertex_properties', to='ontology_model.vertextypepropertydefinition', verbose_name='property_definition'),
        ),
        migrations.AlterField(
            model_name='vertexpropertyassignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='vertexpropertyassignment',
            name='value',
            field=models.JSONField(verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='vertexpropertyassignment',
            name='vertex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ontology.vertex', verbose_name='vertex'),
        ),
    ]
