# Generated by Django 6.0 on 2026-01-06 16:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0018_alter_ontology_options_alter_relationship_options_and_more"),
        ("ontology_model", "0020_datatype_unique_data_type_in_model_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ontology",
            constraint=models.UniqueConstraint(fields=("name",), name="unique_ontology"),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.UniqueConstraint(fields=("name", "ontology"), name="unique_relationship_in_ontology"),
        ),
        migrations.AddConstraint(
            model_name="vertex",
            constraint=models.UniqueConstraint(fields=("name", "ontology"), name="unique_vertex_in_ontology"),
        ),
    ]
