# Generated by Django 5.1.6 on 2025-02-05 19:45
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="имя")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание")),
                ("object_schema", models.JSONField(blank=True, null=True, verbose_name="схема объекта")),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_derivations",
                        to="ontology_model.datatype",
                        verbose_name="отнаследован от",
                    ),
                ),
            ],
            options={
                "verbose_name": "тип данных",
                "verbose_name_plural": "типы данных",
            },
        ),
        migrations.CreateModel(
            name="RelationshipType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="имя")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание")),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_derivations",
                        to="ontology_model.relationshiptype",
                        verbose_name="отнаследован от",
                    ),
                ),
            ],
            options={
                "verbose_name": "тип связи",
                "verbose_name_plural": "типы связей",
            },
        ),
        migrations.CreateModel(
            name="RelationshipTypePropertyDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("default", models.JSONField(blank=True, null=True, verbose_name="значение по умолчанию")),
                ("name", models.CharField(max_length=255, verbose_name="имя свойства")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание свойства")),
                ("required", models.BooleanField(default=False, verbose_name="обязательное")),
                (
                    "allows_multiple",
                    models.BooleanField(default=False, verbose_name="допускает множественное значение"),
                ),
                (
                    "data_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_typed",
                        to="ontology_model.datatype",
                        verbose_name="тип данных",
                    ),
                ),
                (
                    "relationship_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="ontology_model.relationshiptype",
                        verbose_name="тип связи",
                    ),
                ),
            ],
            options={
                "verbose_name": "свойство связи",
                "verbose_name_plural": "свойства связей",
            },
        ),
        migrations.CreateModel(
            name="VertexType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="имя")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание")),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_derivations",
                        to="ontology_model.vertextype",
                        verbose_name="отнаследован от",
                    ),
                ),
            ],
            options={
                "verbose_name": "тип вершины",
                "verbose_name_plural": "типы вершин",
            },
        ),
        migrations.AddField(
            model_name="relationshiptype",
            name="valid_source_vertex_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="valid_relation_source_types",
                to="ontology_model.vertextype",
                verbose_name="возможне типы родительских вершин",
            ),
        ),
        migrations.AddField(
            model_name="relationshiptype",
            name="valid_target_vertex_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="valid_relation_target_types",
                to="ontology_model.vertextype",
                verbose_name="возможне типы дочерних вершин",
            ),
        ),
        migrations.CreateModel(
            name="VertexTypePropertyDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("default", models.JSONField(blank=True, null=True, verbose_name="значение по умолчанию")),
                ("name", models.CharField(max_length=255, verbose_name="имя свойства")),
                ("description", models.TextField(blank=True, null=True, verbose_name="описание свойства")),
                ("required", models.BooleanField(default=False, verbose_name="обязательное")),
                (
                    "allows_multiple",
                    models.BooleanField(default=False, verbose_name="допускает множественное значение"),
                ),
                (
                    "data_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="%(class)s_typed",
                        to="ontology_model.datatype",
                        verbose_name="тип данных",
                    ),
                ),
                (
                    "vertex_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="ontology_model.vertextype",
                        verbose_name="тип вершины",
                    ),
                ),
            ],
            options={
                "verbose_name": "свойство вершины",
                "verbose_name_plural": "свойства вершин",
            },
        ),
    ]
